// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: api/worker/v1/terminal.proto

package workerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkerTerminalService_OpenTerminal_FullMethodName   = "/renderops.worker.v1.WorkerTerminalService/OpenTerminal"
	WorkerTerminalService_CloseTerminal_FullMethodName  = "/renderops.worker.v1.WorkerTerminalService/CloseTerminal"
	WorkerTerminalService_AttachTerminal_FullMethodName = "/renderops.worker.v1.WorkerTerminalService/AttachTerminal"
)

// WorkerTerminalServiceClient is the client API for WorkerTerminalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkerTerminalServiceClient interface {
	OpenTerminal(ctx context.Context, in *OpenTerminalRequest, opts ...grpc.CallOption) (*OpenTerminalResponse, error)
	CloseTerminal(ctx context.Context, in *CloseTerminalRequest, opts ...grpc.CallOption) (*CloseTerminalResponse, error)
	AttachTerminal(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TerminalFrame, TerminalFrame], error)
}

type workerTerminalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerTerminalServiceClient(cc grpc.ClientConnInterface) WorkerTerminalServiceClient {
	return &workerTerminalServiceClient{cc}
}

func (c *workerTerminalServiceClient) OpenTerminal(ctx context.Context, in *OpenTerminalRequest, opts ...grpc.CallOption) (*OpenTerminalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenTerminalResponse)
	err := c.cc.Invoke(ctx, WorkerTerminalService_OpenTerminal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerTerminalServiceClient) CloseTerminal(ctx context.Context, in *CloseTerminalRequest, opts ...grpc.CallOption) (*CloseTerminalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseTerminalResponse)
	err := c.cc.Invoke(ctx, WorkerTerminalService_CloseTerminal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerTerminalServiceClient) AttachTerminal(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TerminalFrame, TerminalFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkerTerminalService_ServiceDesc.Streams[0], WorkerTerminalService_AttachTerminal_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TerminalFrame, TerminalFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerTerminalService_AttachTerminalClient = grpc.BidiStreamingClient[TerminalFrame, TerminalFrame]

// WorkerTerminalServiceServer is the server API for WorkerTerminalService service.
// All implementations must embed UnimplementedWorkerTerminalServiceServer
// for forward compatibility.
type WorkerTerminalServiceServer interface {
	OpenTerminal(context.Context, *OpenTerminalRequest) (*OpenTerminalResponse, error)
	CloseTerminal(context.Context, *CloseTerminalRequest) (*CloseTerminalResponse, error)
	AttachTerminal(grpc.BidiStreamingServer[TerminalFrame, TerminalFrame]) error
	mustEmbedUnimplementedWorkerTerminalServiceServer()
}

// UnimplementedWorkerTerminalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerTerminalServiceServer struct{}

func (UnimplementedWorkerTerminalServiceServer) OpenTerminal(context.Context, *OpenTerminalRequest) (*OpenTerminalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenTerminal not implemented")
}
func (UnimplementedWorkerTerminalServiceServer) CloseTerminal(context.Context, *CloseTerminalRequest) (*CloseTerminalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseTerminal not implemented")
}
func (UnimplementedWorkerTerminalServiceServer) AttachTerminal(grpc.BidiStreamingServer[TerminalFrame, TerminalFrame]) error {
	return status.Errorf(codes.Unimplemented, "method AttachTerminal not implemented")
}
func (UnimplementedWorkerTerminalServiceServer) mustEmbedUnimplementedWorkerTerminalServiceServer() {}
func (UnimplementedWorkerTerminalServiceServer) testEmbeddedByValue()                               {}

// UnsafeWorkerTerminalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerTerminalServiceServer will
// result in compilation errors.
type UnsafeWorkerTerminalServiceServer interface {
	mustEmbedUnimplementedWorkerTerminalServiceServer()
}

func RegisterWorkerTerminalServiceServer(s grpc.ServiceRegistrar, srv WorkerTerminalServiceServer) {
	// If the following call pancis, it indicates UnimplementedWorkerTerminalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkerTerminalService_ServiceDesc, srv)
}

func _WorkerTerminalService_OpenTerminal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenTerminalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerTerminalServiceServer).OpenTerminal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerTerminalService_OpenTerminal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerTerminalServiceServer).OpenTerminal(ctx, req.(*OpenTerminalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerTerminalService_CloseTerminal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseTerminalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerTerminalServiceServer).CloseTerminal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerTerminalService_CloseTerminal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerTerminalServiceServer).CloseTerminal(ctx, req.(*CloseTerminalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerTerminalService_AttachTerminal_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorkerTerminalServiceServer).AttachTerminal(&grpc.GenericServerStream[TerminalFrame, TerminalFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerTerminalService_AttachTerminalServer = grpc.BidiStreamingServer[TerminalFrame, TerminalFrame]

// WorkerTerminalService_ServiceDesc is the grpc.ServiceDesc for WorkerTerminalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerTerminalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "renderops.worker.v1.WorkerTerminalService",
	HandlerType: (*WorkerTerminalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OpenTerminal",
			Handler:    _WorkerTerminalService_OpenTerminal_Handler,
		},
		{
			MethodName: "CloseTerminal",
			Handler:    _WorkerTerminalService_CloseTerminal_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AttachTerminal",
			Handler:       _WorkerTerminalService_AttachTerminal_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/worker/v1/terminal.proto",
}
